<?php
use Stephane888\Debug\debugLog;
use Drupal\migrateexport\Services\ManageNodes;
use Drupal\migrateexport\Services\ManageEntities;

function migrateexport_menu() {
  $items = [];
  $items['migrateexport/entities-definitions'] = array(
    'title' => "Reupere toutes les definitions d'entites",
    'description' => "Reupere toutes les definitions d'entites",
    'page callback' => 'migrateexport_entities_definitions_callback',
    'access callback' => true
  );
  $items['migrateexport/migrate-export-entities/%/%'] = array(
    'title' => "Recupere la definition d'une entité",
    'description' => "Recupere la definition d'une entité, y compris les
  bunbles ...",
    'page callback' => 'migrateexport_entitity_definition_callback',
    'page arguments' => [
      'entity_type_id' => 2,
      'bundle' => 3
    ],
    'access callback' => true
  );
  $items['migrateexport/export-import-entities/show-site-config'] = [
    'title' => 'Books View',
    'description' => 'Books Information',
    'page callback' => 'migrateexport_site_info_callback',
    'access callback' => true
  ];
  $items['migrateexport/export-import-entities/load-entitties/%/%/%/%'] = [
    'title' => 'Load entitties',
    'description' => 'Books Information',
    'page callback' => 'migrateexport_load_entities',
    'access callback' => true,
    'page arguments' => [
      'entity_type_id' => 3,
      'bundle' => 4,
      'page' => 5,
      'length' => 6
    ]
  ];
  return $items;
}

/**
 * --
 */
function migrateexport_load_entities($entity_type_id, $bundle, $page, $length) {
  $ManageEntities = new ManageEntities();
  return drupal_json_output($ManageEntities->loadEntities($entity_type_id, $bundle, $page, $length));
}

/**
 * --
 *
 * @param string $entity_type_id
 * @param string $bundle
 */
function migrateexport_entitity_definition_callback($entity_type_id, $bundle) {
  // /////////////
  // _addcustom_resquest();
  $ManageEntities = new ManageEntities();
  return drupal_json_output($ManageEntities->loadFullDefinitionOfentityAndbundle($entity_type_id, $bundle));
}

/**
 *
 * @return string[]
 */
function migrateexport_entities_definitions_callback() {
  $ManageEntities = new ManageEntities();
  return drupal_json_output($ManageEntities->LoadAllentities());
}

function migrateexport_site_info_callback() {
  $ManageNodes = new ManageNodes();
  $results = $ManageNodes->loadAllTypes();
  $results['time2'] = time();
  return drupal_json_output($results);
}

/**
 * Implémente hook_init().
 * Desactive le cache sur les routes suivantes.
 */
function migrateexport_init() {
  if (str_contains(current_path(), "migrateexport")) {
    drupal_page_is_cacheable(FALSE);
    _addcustom_resquest();
  }
}

function _addcustom_resquest() {
  $allowed_origins = [
    'http://you-v10.kksa',
    'http://impact.local',
    'http://you-test-v10.kksa',
    'http://you.local'
  ];
  // Doit etre un paramettre configurable.
  if (isset($_SERVER['HTTP_ORIGIN']) && in_array($_SERVER['HTTP_ORIGIN'], $allowed_origins))
    drupal_add_http_header("Access-Control-Allow-Origin", $_SERVER['HTTP_ORIGIN']);
  drupal_add_http_header("Access-Control-Allow-Headers", 'x-csrf-token', true);
  drupal_add_http_header("Access-Control-Allow-Headers", 'authorization', true);
  drupal_add_http_header("Access-Control-Allow-Headers", 'x-allowed-header', true);
  drupal_add_http_header("Access-Control-Allow-Headers", 'content-disposition', true);
  drupal_add_http_header("Access-Control-Allow-Headers", 'x-requested-with', true);
  drupal_add_http_header("Access-Control-Allow-Headers", 'content-type', true);
  drupal_add_http_header("Access-Control-Allow-Headers", 'request-starttime', true);
}
